"""added extended table

Revision ID: 12cd33a525a1
Revises: 0ec0f0951601
Create Date: 2026-03-08 00:14:05.714321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12cd33a525a1'
down_revision: Union[str, None] = '0ec0f0951601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extended',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('extended_date', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('extended_by_mentor_id', sa.Integer(), nullable=False),
    sa.Column('extended_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['extended_by_mentor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extended_id'), 'extended', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extended_id'), table_name='extended')
    op.drop_table('extended')
    # ### end Alembic commands ###
