"""evaluated_by_mentor

Revision ID: 291cd0600f17
Revises: 123068841e39
Create Date: 2026-01-21 22:56:14.641248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '291cd0600f17'
down_revision: Union[str, None] = '123068841e39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_statusupdate_member_sent_date'), table_name='statusupdatehistory')
    op.drop_table('statusupdatehistory')
    op.drop_table('_sqlx_migrations')
    op.drop_index(op.f('idx_sessions_token_hash'), table_name='sessions')
    op.drop_index(op.f('idx_apikeys_key_hash'), table_name='apikeys')
    op.drop_table('statusbreaks')
    op.drop_table('attendance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('attendance_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('is_present', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('time_in', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('time_out', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint('is_present = false OR date <= CURRENT_DATE', name=op.f('attendance_check1')),
    sa.CheckConstraint('is_present = true AND time_in IS NOT NULL AND time_out IS NOT NULL OR is_present = false AND time_in IS NULL AND time_out IS NULL', name=op.f('attendance_check')),
    sa.CheckConstraint('time_out IS NULL OR time_out >= time_in', name=op.f('attendance_check2')),
    sa.ForeignKeyConstraint(['member_id'], ['member.member_id'], name=op.f('attendance_member_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attendance_id', name=op.f('attendance_pkey')),
    sa.UniqueConstraint('member_id', 'date', name=op.f('attendance_member_id_date_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('statusbreaks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('statusbreaks_pkey'))
    )
    op.create_table('apikeys',
    sa.Column('api_key_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('key_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_used_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['member.member_id'], name=op.f('apikeys_created_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('api_key_id', name=op.f('apikeys_pkey'))
    )
    op.create_index(op.f('idx_apikeys_key_hash'), 'apikeys', ['key_hash'], unique=False)
    op.create_table('sessions',
    sa.Column('session_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.member_id'], name=op.f('sessions_member_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', name=op.f('sessions_pkey'))
    )
    op.create_index(op.f('idx_sessions_token_hash'), 'sessions', ['token_hash'], unique=False)
    op.create_table('_sqlx_migrations',
    sa.Column('version', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('installed_on', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('success', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('checksum', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('execution_time', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version', name=op.f('_sqlx_migrations_pkey'))
    )
    op.create_table('statusupdatehistory',
    sa.Column('update_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('is_sent', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.member_id'], name=op.f('statusupdatehistory_member_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('update_id', name=op.f('statusupdatehistory_pkey')),
    sa.UniqueConstraint('member_id', 'date', name=op.f('statusupdatehistory_member_id_date_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_statusupdate_member_sent_date'), 'statusupdatehistory', ['member_id', 'is_sent', 'date'], unique=False)
    op.create_table('member',
    sa.Column('member_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('roll_no', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('sex', postgresql.ENUM('M', 'F', 'Other', name='sex_type'), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hostel', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('mac_address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('discord_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('track', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('github_user', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('role', postgresql.ENUM('Admin', 'Member', 'Bot', name='role_type'), server_default=sa.text("'Member'::role_type"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('year >= 1 AND year <= 4', name=op.f('member_year_check')),
    sa.PrimaryKeyConstraint('member_id', name=op.f('member_pkey')),
    sa.UniqueConstraint('discord_id', name=op.f('member_discord_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('email', name=op.f('member_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('mac_address', name=op.f('member_mac_address_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('roll_no', name=op.f('member_roll_no_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
