"""remove reference_link from submissions

Revision ID: 40774b92ab4a
Revises: 8f84ff4de4af
Create Date: 2025-08-05 09:27:59.401932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40774b92ab4a'
down_revision: Union[str, None] = '8f84ff4de4af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'reference_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('reference_link', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
