"""added tables

Revision ID: 5e0c51d8187f
Revises: 4ba7992b5758
Create Date: 2026-01-29 23:13:22.666137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e0c51d8187f'
down_revision: Union[str, None] = '4ba7992b5758'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extended',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('extended_date', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extended_id'), 'extended', ['id'], unique=False)
    op.create_table('pause',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('pause_date', sa.DateTime(), nullable=False),
    sa.Column('resume_date', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pause_id'), 'pause', ['id'], unique=False)
    op.add_column('submissions', sa.Column('evaluated_by_mentor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'submissions', 'users', ['evaluated_by_mentor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_column('submissions', 'evaluated_by_mentor_id')
    op.drop_index(op.f('ix_pause_id'), table_name='pause')
    op.drop_table('pause')
    op.drop_index(op.f('ix_extended_id'), table_name='extended')
    op.drop_table('extended')
    # ### end Alembic commands ###
