"""evaluated_by_mentor

Revision ID: e1bff3eb6825
Revises: 095cfebc62c3
Create Date: 2026-01-21 23:01:02.607708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1bff3eb6825'
down_revision: Union[str, None] = '095cfebc62c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apikeys')
    op.drop_table('sessions')
    op.drop_table('member')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('member_id', sa.INTEGER(), server_default=sa.text("nextval('member_member_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('roll_no', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('sex', postgresql.ENUM('M', 'F', 'Other', name='sex_type'), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hostel', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('mac_address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('discord_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('track', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('github_user', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('role', postgresql.ENUM('Admin', 'Member', 'Bot', name='role_type'), server_default=sa.text("'Member'::role_type"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('year >= 1 AND year <= 4', name='member_year_check'),
    sa.PrimaryKeyConstraint('member_id', name='member_pkey'),
    sa.UniqueConstraint('discord_id', name='member_discord_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('email', name='member_email_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('mac_address', name='member_mac_address_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('roll_no', name='member_roll_no_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('sessions',
    sa.Column('session_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.member_id'], name=op.f('sessions_member_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', name=op.f('sessions_pkey'))
    )
    op.create_table('apikeys',
    sa.Column('api_key_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('key_hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_used_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['member.member_id'], name=op.f('apikeys_created_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('api_key_id', name=op.f('apikeys_pkey'))
    )
    # ### end Alembic commands ###
