"""delete user

Revision ID: fcec17f00c03
Revises: 4ba7992b5758
Create Date: 2026-02-15 22:17:03.645070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcec17f00c03'
down_revision: Union[str, None] = '4ba7992b5758'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_mentor_mentee_map_mentee_id'), 'mentor_mentee_map', ['mentee_id'], unique=False)
    op.create_index(op.f('ix_mentor_mentee_map_mentor_id'), 'mentor_mentee_map', ['mentor_id'], unique=False)
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)

    op.execute("""
        CREATE OR REPLACE FUNCTION handle_user_delete()
        RETURNS trigger AS $$
        BEGIN
            DELETE FROM mentor_mentee_map
            WHERE mentor_id = NEW.id
            OR mentee_id = NEW.id;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)

    op.execute("""
        CREATE TRIGGER user_delete_trigger
        AFTER UPDATE ON users
        FOR EACH ROW
        WHEN (OLD.deleted_at IS NULL AND NEW.deleted_at IS NOT NULL)
        EXECUTE FUNCTION handle_user_delete();
    """)
    

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_column('users', 'deleted_at')
    op.drop_index(op.f('ix_mentor_mentee_map_mentor_id'), table_name='mentor_mentee_map')
    op.drop_index(op.f('ix_mentor_mentee_map_mentee_id'), table_name='mentor_mentee_map')
    op.execute("DROP TRIGGER IF EXISTS user_delete_trigger ON users;")
    op.execute("DROP FUNCTION IF EXISTS handle_user_delete();")
    # ### end Alembic commands ###
